# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1507tol87Ntjxiqm9p-GhKSb3XUBFNyFE
"""

num = 7
result = "Even" if num % 2 == 0 else "Odd"
print(result)

d1 = {'x': 1, 'y': 2}
d2 = {'y': 3, 'z': 4}
d1.update(d2)
print(d1)

for i in range(1, 4):
    for j in range(1, i + 1):
        if i * j % 2 == 0:
            print(i, j)
            break

numbers = [1, 2, 3, 4]

squares = [n ** 2 for n in numbers if n % 2 == 0]
print(squares)

for i in range(4):
    for j in range(4):
        if i == 2:
            continue
        if j == 3:
            break
        print(i, j)






i = 0
while i < 5:
    if i == 3:
        break
    print(i, end=" ")
    i += 1
else:
    print("Loop End")
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}
result = set1.difference_update(set2)
print(result)

num = 10
print(num / 3)


my_dict = {'a': 1, 'b': 2}
new_dict = my_dict.copy()
new_dict['a'] = 3
print(my_dict['a'])

# variable length argument (*var)
def func(*data):
  print(data, type(data))

func()
func(10,20)
func(10,20,"abc")

# keyword variable length argument (**var)
def func(**data):
  print(data, type(data))

func(eid=10, salary=20)
func(eid=10, salary=20, name="abc")

#  first class function
# 1.assigned to variable
# 2.passed the function as a parameter to another parameter
# 3.return the function from a function

def func():
  print("hello")

x=func   # we have assigne function to a variable
func()
x()